package services

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/opendeploy/opendeploy/internal/exec"
	"go.uber.org/zap"
)

type AvahiService struct {
	runner *exec.Runner
	logger *zap.Logger
}

func NewAvahiService(runner *exec.Runner, logger *zap.Logger) *AvahiService {
	return &AvahiService{runner: runner, logger: logger}
}

// EnsureOptimalConfig ensures Avahi is configured optimally for WiFi network switching
func (a *AvahiService) EnsureOptimalConfig(ctx context.Context) error {
	configPath := "/etc/avahi/avahi-daemon.conf"

	// Check if config file exists
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		a.logger.Warn("Avahi config file not found, skipping configuration")
		return nil
	}

	// Read current config
	content, err := os.ReadFile(configPath)
	if err != nil {
		a.logger.Warn("Failed to read Avahi config, skipping optimization", zap.Error(err))
		return nil // Don't fail WiFi connection if we can't read config
	}

	currentConfig := string(content)
	needsUpdate := false

	// Check if optimal settings are present
	requiredSettings := []string{
		"use-ipv4=yes",
		"use-ipv6=no",
		"allow-interfaces=wlan0",
		"publish-addresses=yes",
		"publish-hinfo=yes",
		"publish-workstation=yes",
		"publish-domain=yes",
	}

	for _, setting := range requiredSettings {
		if !contains(currentConfig, setting) {
			needsUpdate = true
			a.logger.Info("Missing Avahi setting", zap.String("setting", setting))
			break
		}
	}

	if needsUpdate {
		a.logger.Info("Avahi config needs optimization, updating...")
		if err := a.writeOptimalConfig(ctx, configPath); err != nil {
			a.logger.Warn("Failed to update Avahi config", zap.Error(err))
			return nil // Don't fail WiFi connection if config update fails
		}
		a.logger.Info("Avahi config optimized successfully")
	} else {
		a.logger.Debug("Avahi config already optimal")
	}

	return nil
}

// writeOptimalConfig writes an optimized Avahi configuration
func (a *AvahiService) writeOptimalConfig(ctx context.Context, configPath string) error {
	optimalConfig := `# Avahi daemon configuration - Optimized for OpenDeploy
# Auto-generated by OpenDeploy WiFi service
# Last updated: ` + time.Now().Format(time.RFC3339) + `

[server]
use-ipv4=yes
use-ipv6=no
allow-interfaces=wlan0
ratelimit-interval-usec=1000000
ratelimit-burst=1000

[wide-area]
enable-wide-area=yes

[publish]
publish-addresses=yes
publish-hinfo=yes
publish-workstation=yes
publish-domain=yes

[reflector]
#enable-reflector=no

[rlimits]
#rlimit-core=0
#rlimit-data=8388608
#rlimit-fsize=0
#rlimit-nofile=768
#rlimit-stack=8388608
#rlimit-nproc=3
`

	// Backup existing config with timestamp
	backupPath := configPath + ".backup." + time.Now().Format("20060102-150405")
	backupResult, _ := a.runner.Run(ctx, exec.RunOpts{
		JobType: "backup_avahi_config",
		Command: "sudo",
		Args:    []string{"cp", configPath, backupPath},
		Timeout: 5 * time.Second,
	})
	if backupResult != nil && backupResult.Success {
		a.logger.Info("Backed up existing Avahi config", zap.String("backup", backupPath))
	}

	// Write new config to temp file
	tmpFile := "/tmp/avahi-daemon.conf.new"
	if err := os.WriteFile(tmpFile, []byte(optimalConfig), 0644); err != nil {
		return fmt.Errorf("writing temp config: %w", err)
	}

	// Move to actual location with sudo
	moveResult, err := a.runner.Run(ctx, exec.RunOpts{
		JobType: "update_avahi_config",
		Command: "sudo",
		Args:    []string{"mv", tmpFile, configPath},
		Timeout: 5 * time.Second,
	})
	if err != nil || !moveResult.Success {
		// Clean up temp file
		os.Remove(tmpFile)
		return fmt.Errorf("moving config to /etc: %w", err)
	}

	// Set proper permissions
	_, _ = a.runner.Run(ctx, exec.RunOpts{
		JobType: "set_avahi_permissions",
		Command: "sudo",
		Args:    []string{"chmod", "644", configPath},
		Timeout: 5 * time.Second,
	})

	a.logger.Info("Avahi config updated successfully", zap.String("path", configPath))
	return nil
}

// Restart restarts the Avahi daemon
func (a *AvahiService) Restart(ctx context.Context) error {
	a.logger.Info("Restarting Avahi daemon to refresh hostname announcement...")

	result, err := a.runner.Run(ctx, exec.RunOpts{
		JobType: "restart_avahi",
		Command: "sudo",
		Args:    []string{"systemctl", "restart", "avahi-daemon"},
		Timeout: 10 * time.Second,
	})
	if err != nil || !result.Success {
		a.logger.Error("Failed to restart Avahi daemon", zap.Error(err))
		return fmt.Errorf("restarting avahi: %w", err)
	}

	// Wait for Avahi to start broadcasting on the new network
	time.Sleep(2 * time.Second)

	// Verify it's actually running
	isActive, _ := a.CheckStatus(ctx)
	if isActive {
		a.logger.Info("Avahi daemon restarted successfully - hostname should now be accessible")
	} else {
		a.logger.Warn("Avahi daemon restart completed but service is not active")
	}

	return nil
}

// CheckStatus checks if Avahi daemon is running
func (a *AvahiService) CheckStatus(ctx context.Context) (bool, error) {
	result, err := a.runner.Run(ctx, exec.RunOpts{
		JobType: "check_avahi_status",
		Command: "sudo",
		Args:    []string{"systemctl", "is-active", "avahi-daemon"},
		Timeout: 5 * time.Second,
	})
	if err != nil {
		return false, err
	}

	return result.Success, nil
}

// RefreshHostname forces Avahi to re-announce the hostname on the network
// This should be called after every WiFi network switch to ensure .local hostname works
func (a *AvahiService) RefreshHostname(ctx context.Context) error {
	// First ensure optimal configuration is applied
	if err := a.EnsureOptimalConfig(ctx); err != nil {
		a.logger.Warn("Failed to ensure optimal Avahi config", zap.Error(err))
		// Continue anyway - config might already be good
	}

	// Check if Avahi is installed and available
	result, err := a.runner.Run(ctx, exec.RunOpts{
		JobType: "check_avahi_installed",
		Command: "which",
		Args:    []string{"avahi-daemon"},
		Timeout: 5 * time.Second,
	})
	if err != nil || !result.Success {
		a.logger.Warn("Avahi daemon not found on system, skipping hostname refresh")
		return nil
	}

	// Check if Avahi is running
	isActive, err := a.CheckStatus(ctx)
	if err != nil {
		a.logger.Warn("Failed to check Avahi status", zap.Error(err))
	}

	if !isActive {
		a.logger.Info("Avahi is not active, starting it...")
		startResult, err := a.runner.Run(ctx, exec.RunOpts{
			JobType: "start_avahi",
			Command: "sudo",
			Args:    []string{"systemctl", "start", "avahi-daemon"},
			Timeout: 10 * time.Second,
		})
		if err != nil || !startResult.Success {
			a.logger.Error("Failed to start Avahi daemon", zap.Error(err))
			return fmt.Errorf("failed to start avahi daemon")
		}
		time.Sleep(2 * time.Second)
	}

	// Restart to force re-announcement on new network
	return a.Restart(ctx)
}

func contains(s, substr string) bool {
	return len(s) >= len(substr) && (s == substr || len(s) > len(substr) &&
		(findSubstring(s, substr) >= 0))
}

func findSubstring(s, substr string) int {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}
